#!/bin/bash

#We need to change mode and give permission before executing this file
#chmod 755 specs

#get data and store them in variables
username=$(whoami | awk '{print $1}')
year=$(date | awk '{print $6}')
month=$(date | awk '{print $2}')
day=$(date | awk '{print $3}')
time=$(date | awk '{print $4}')
gmt=$(date | awk '{print $5}')
creationDate=$(who | awk '{print $3}')
creationTime=$(who | awk '{print $4}')
permission=$(who | awk '{print $2}')
host=$(hostname | awk '{print $1}')
numOfUsers=$(w | awk '/load average/ {print $4}')
os=$(uname | awk '{print $1}')
CPUFamily=$(lscpu | awk '/CPU family:/ {print $3}')
model=$(lscpu | awk '/Model name:/ {print $3 " " $4 " " $5 " " $6 " " $7 " " $8}')
freq=$(lscpu | awk '/CPU MHz:/ {print $3}')

#print them in formatted output
printf "			 ABOUT USER AND STATE OF SYSTEM\n\n"
printf "%s: %40s\n" "username" "$username"
printf "%s: %40s\n" "System Created" "$creationDate $creationTime"
printf "%s: %49s\n\n" "Current Date & Time" "$month $day, $year $time (GMT $gmt)"

printf "%s: %27s\n" "Operating System" "$os"
printf "%s: %24s\n" "Number of Users" "$numOfUsers"
printf "%s: %51s\n" "hostname" "$host"
printf "%s: %31s\n\n" "Permissions" "$permission"


printf "			      ABOUT LAPTOP AND CPU\n\n"
printf "%s: %33s\n" "Family" "$CPUFamily"
printf "%s: %69s\n" "CPU Model" "$model"
printf "%s: %37s\n" "Frequency" "$freq"


